### ISSUE TITLE
Create a new attribute for a signal

### ISSUE THREAD

**Issue by Sharpe49** [ts2/ts2-sim-server#37]
For the Gretz map, I need a new attribute for the signal : if I set this parameter to true, this signal is not the end of a block section and the inbound signal shall take the track sections after the ignored signal into account for the track occupancy.

**Comment by npiganeau** [comment]
Track occupancy takes into account the whole route if there is a route starting from the first signal or up to the next signal if there is no route set (e.g. automatic signals). 
Then you can use the already existing "ROUTE_SET_ACROSS" attribute to manage the signal in the middle.

Like in this example [fr-test.zip](https://github.com/ts2/ts2-sim-server/files/3726085/fr-test.zip).

Would this work for you ?

**Comment by Sharpe49** [comment]
No, that would not solve my issue.
In order to model correctly bidirectionnal tracks, the route has to go to the next route signal in order to lock correctly the track (in order not to have a train coming in the opposite direction on the same track.
If there is a block (automatic) signal between the origin signal and the destination signal, it is ignored.
For example, here's the latest version of Gretz-Armainvilliers. You have an example of what I mean on the single track line (which is managed by Tournan signal box).
[gretz-armainvilliers.zip](https://github.com/ts2/ts2-sim-server/files/3883710/gretz-armainvilliers.zip)

**Comment by npiganeau** [comment]
I understand the need, but I don't see why this example [fr-test.zip](https://github.com/ts2/ts2-sim-server/files/3883897/fr-test.zip) doesn't solve it:
- The block signal in between is not taken into account by the entry route signal for route occupancy (run the sim to see the train. The entry signal remains red even after the train passed the block signal).
- The block signal can be configured however you want independently from the route signal (probably not like the one in the example though!), using all usual conditions.

**Comment by Sharpe49** [comment]
You can take a look at this video. It shows me investigating the issue.
https://youtu.be/A0SFgVu84SY?t=17682

And just before, I discovered another problem : editing the initial state value of a route provokes a crash.
https://youtu.be/A0SFgVu84SY?t=17623

**Comment by npiganeau** [comment]
Ok. If I understand it well, you want an entry route signal that compute its aspect by taking into account:
- The next signal state (possibly a block signal)
- The presence of a train on the whole route and not only before the next signal

Am I correct ?

In this case, I suggest the following:

- I will change the behaviour of "next signal aspect" to take into account the actual next signal (In the current implementation, it takes into account the aspect of the exit signal of the route if this signal is the entry or the next signal on the line otherwise).
- But this will break the behaviour of route signals with CV/M signals in the middle. So I will add a new condition "route exit signal aspect" that will work the same way as the current "next signal aspect" implementation. You will then have to upgrade your Gretz simulation to work.
- Keep the "train present" and "train not present" implementation that takes into account the whole route if a route is set from this signal and before the next signal aspect otherwise.

Would that solve your problem ?

**Comment by npiganeau** [comment]
I watched the video to the end.

Here is what I will do. I will make the following conditions available:
- TRAIN_NOT_PRESENT_ON_NEXT_ROUTE will be modified to do exactly what it says. If no route is set then the condition will be always false.
- TRAIN_NOT_PRESENT_BEFORE_NEXT_SIGNAL will be added. It will be true if there is no train in the next block
- NEXT_SIGNAL_ASPECTS will be modified to take into account only the next signal aspect
- ROUTE_EXIT_SIGNAL_ASPECTS will be added to take into account the exit signal of the route. If no route is set, the condition will always be false.

Then you can update the FR signal library where needed.

**Comment by npiganeau** [comment]
I watched the video to the end.

Here is what I will do. I will make the following conditions available:
- TRAIN_NOT_PRESENT_ON_NEXT_ROUTE will be modified to do exactly what it says. If no route is set then the condition will be always false.
- TRAIN_NOT_PRESENT_BEFORE_NEXT_SIGNAL will be added. It will be true if there is no train in the next block
- NEXT_SIGNAL_ASPECTS will be modified to take into account only the next signal aspect
- ROUTE_EXIT_SIGNAL_ASPECTS will be added to take into account the exit signal of the route. If no route is set, the condition will always be false.

Then you can update the FR signal library where needed.

**Comment by npiganeau** [comment]
Check version 0.7.7 on the ts2 project.

You'll have to update the signal library in your sim to see the effect.

**Comment by Sharpe49** [comment]
Ok, I'll try it this evening.
Does it work also for the dwarf signal which must be ignored (in that case, it's the next block or route signal which must be taken into account) ?

**Comment by npiganeau** [comment]
I try to keep the conditions as generic as possible.

So for the dwarf signal, you can use the ROUTE_EXIT_SIGNAL_ASPECTS so that it does not take into account the next signal but the next route signal, if the dwarf signal is the only intermediate signal on the line.

If not, it is more tricky, but still possible:

Consider the case :
```
Route Signal (1) -> Dwarf Signal (2) -> Block Signal (3) -> Route Signal (4). 
```

In this case, I would compute the signal state of (1) by using NEXT_SIGNAL_ASPECTS and create several aspects for the dwarf signal (2) that would all show the same on the screen but would be technically different aspects depending on the aspect of signal (3) to forward the info to signal (1).

For example:
- (2) shows "M-S" (displays M) when (3) is S and configure (1) to show A when next signal is "M-S"
- (2) shows "M-A" (displays M) when (3) is A and configure (1) to show VL when next signal is "M-A"
etc.

**Comment by npiganeau** [comment]
I forgot to say that you must redownload the server too in File=>Options

**Comment by Sharpe49** [comment]
I think it would be easier to have some parameter saying that the dwarf signal must be ignored and, in that case, the algorithm will try to find the next signal on the route.
Or perhaps, some overriding parameter called "NEXT_SIGNAL" telling the simulator which signal is the next one. If it is not set, then the server determine which signal is the next.

For the server, don't worry, I am compiling the server and I am watching the repository.
I still don't know how to code in Go, but I know how to build the app. :)

**Comment by npiganeau** [comment]
I'd rather not add any new parameter to signals and do it with conditions as much as possible to keep it generic.

**New proposal:**

Allow to add a `!` at the end of a NEXT_SIGNAL_ASPECTS item meaning "if you find this aspect, then check next signals with the same data" and this recursively.

Example:

```json
                {
                    "__type__": "SignalState",
                    "aspectName": "FR_BAL_VL",
                    "conditions": {
                        "TRAIN_NOT_PRESENT_ON_NEXT_ROUTE": [],
                        "NEXT_SIGNAL_ASPECTS": [
                            "FR_BAL_VL",
                            "FR_BAL_ACLI",
                            "FR_BAL_RCLI",
                            "FR_BAL_RCLI_ACLI",
                            "FR_BAL_M!"
                        ]
                    }
                }
```
And the condition would be true if 
- there is no train on the next route
- AND
   - the next signal aspect is one of `FR_BAL_VL`, `FR_BAL_ACLI`, `FR_BAL_RCLI`, `FR_BAL_RCLI_ACLI`
   - OR the next signal is `FR_BAL_M` and the next signal afterwards meets the same condition (and so it works recursively with as many dwarf signals showing `FR_BAL_M` in line).

Now if you're interested in the code, all we are talking about starts [here](https://github.com/ts2/ts2-sim-server/blob/6c71e70e7749ebda94aa7295b32bada0a877cb29/simulation/track_signals.go#L440), which leads us [here](https://github.com/ts2/ts2-sim-server/blob/6c71e70e7749ebda94aa7295b32bada0a877cb29/simulation/track_signals.go#L240).

After a few bounces you'll end up in the `simulation/signal_conditions.go` file which is where the functional logic is implemented for each condition through the `Solve()` method. This method takes 3 arguments:
- `item` which is the signal item we want to check the condition for
- `values` which is the list defined in the signal library for the condition (e.g. applicable signal states for the NEXT_SIGNAL_ASPECTS condition)
- `params` which is the list defined in the editor for a specific signal if any (e.g. route numbers for the ROUTES_SET condition)

**Comment by Sharpe49** [comment]
Hmm, I think this algorithm should work, but I will use the FR_BAL_M_DISCARD aspect which is specific to dwarf signals.

**Comment by npiganeau** [comment]
Ok. I'll implement the `!` tonight.

**Comment by npiganeau** [comment]
Done. You'll need to rebuild the server or download v0.7.5.

Here is my example sim with an automatic signal and 2 dwarf signals: 
[fr-test.zip](https://github.com/ts2/ts2-sim-server/files/3898720/fr-test.zip)

I guess this is what you wanted. Am I right ?

You can check the signal library inside the file. I modified:
- "FR_BAL_C_A_R_RCLI_VL_AUTO" signal type:
    - I put "TRAIN_NOT_PRESENT_BEFORE_NEXT_SIGNAL" instead of "TRAIN_NOT_PRESENT_ON_NEXT_ROUTE"
    - I added "FR_BAL_M_DISCARD!"
- "FR_BAL_S_A_R_RCLI_VL" signal type:
    - I added "FR_BAL_M_DISCARD!"

I let you modify the "official" FR signal library on ts2-data, because you know better than me how signals should behave.

**Comment by Sharpe49** [comment]
Ok, it works correctly.

I still have some trouble with BAPR signals : 
![BAPR](https://user-images.githubusercontent.com/375720/69769891-1f344d80-1187-11ea-82d7-5c84e8a1e7e8.png)
For the train 117326, there is a clear aspect at the signal near the "COULOMMIERS SAS" place. In that case, it should be red because the block section ends at the third signal at Faremoutiers (the two previous ones are only announcement signals and they do not take the block into account).
This is how it should work :
![BAPR](http://www.cheminots.net/forum/uploads/post-1009-0-71220800-1405756722.png)
Can I use the ! symbol to ignore the announcement signal (the route signal or the block signal doesn't announce another signal) ?

Also, I have a small problem with the automatic signals. They do not update when the train has passed them in the opposite direction and they are still showing the semaphore. Any idea ?

**Comment by npiganeau** [comment]
For BAPR, if you route block by block, you could use TRAIN_NOT_PRESENT_ON_NEXT_ROUTE instead of TRAIN_NOT_PRESENT_BEFORE_NEXT_SIGNAL (which should be used for BAL).

If not, then you can still use TRAIN_NOT_PRESENT_ON_ITEMS and list all the items of the block.

This makes me think that we still have one problem as TRAIN_NOT_PRESENT_BEFORE_NEXT_SIGNAL won't work with a dwarf signal. I think I will add a parameter to this condition such as "FR_BAL_M_DISCARD!" to discard signals when it comes to checking train presence.

I'll check about the opposite signal not updating.

**Comment by npiganeau** [comment]
I've just made a new release.

I think it all works like you want now. Check [fr-test.zip](https://github.com/ts2/ts2-sim-server/files/3907469/fr-test.zip) with BAL and BAPR, in particular when the train passes.

I've made a few modifications in the signal library inside the file for the whole thing to work, you can have a look.

**Comment by Sharpe49** [comment]
For the announcement signal to be ignored by the previous signal, the change on the TRAIN_NOT_PRESENT_BEFORE_NEXT_SIGNAL may solve completely the problem. I'll do some tests on the Gretz line.

By the way, for BAPR, I am not currently using routes from one block signal to another. In the Gretz line, I have routes across a BAPR block signal.

If you want, we can talk on Skype or Discord in order to work together on the best solution. It will probably be easier than exchanging text messages.

Do you have any way to update all signals inside a line ? I am currently replacing manually the signal library inside the json file then remove useless signal definitions by saving the file in the editor.

**Comment by npiganeau** [comment]
In the very last version, I added a new button "Reload Signal Library" which loads the local signal library (i.e. tsl files) in the simulation, overwriting signal aspects and signal types with the same name.

**Comment by Sharpe49** [comment]
Great, that will be really helpful.
About having a talk about the signals, do you want to do it ?

**Comment by npiganeau** [comment]
Yes, I'll send you an email.

**Comment by Sharpe49** [comment]
Fixed a long time ago.
